### ISSUE TITLE
no providers listed after creating new image

### ISSUE THREAD

**Issue by dajohnso** [aeolus-incubator/tim#100]
Pre tim, after I created a image to be built, the image details page would display with a list of providers that are associated with that environment giving the option to select which providers to build for.

![pre-tim](https://f.cloud.github.com/assets/477564/94532/20e2c076-664e-11e2-9816-272b54c90f58.png)

Now that tim is in place, after I create a image, I get no providers shown with a build all button.  Once clicking build all, the providers show up.

![post-tim](https://f.cloud.github.com/assets/477564/94531/2055f43e-664e-11e2-9c3a-4c0a2b2929b7.png)

**Comment by jprovaznik** [comment]
This fixes Matt's pull request which was merged today:
https://github.com/aeolusproject/conductor/pull/363

If you hit an issue in Conductor, it's better to create new issue under aeolus/conductor (not tim).

**Comment by dajohnso** [comment]
ah, ok, I wasn;t sure where this fell.... since it had tim in the url I default to it   :)
