### ISSUE TITLE
Renaming according to new Aeolus glossary

### ISSUE THREAD

**Issue by jistr** [aeolus-incubator/tim#103]
These names are being changed across all Aeolus subprojects:
- Image Template -> Component Outline
- Deployable -> AppForm Blueprint
- Deployment -> AppForm
- Pool Family/Environment-> Cloud Environment
- Pool -> Resource Zone
- Provider -> Cloud Provider

All related materials (docs, wikis etc.) should be updated as well.

For Tim, probably just Image Template name change is relevant.

**Comment by jguiditta** [comment]
If this is still desired, we can reopen, but I think currently this does not fit wit the Tim direction
