### ISSUE TITLE
Logging process guide

### ISSUE THREAD

**Issue by mtaylor** [aeolus-incubator/tim#115]
Unfortunately we carried on the bad practice of not using logging.  When we moved from conductor to Tim.

We need to stop doing this.  This task should include writing a logging guide.  When is appropriate to use each log level and when is appropriate to log.

**Comment by mtaylor** [comment]
https://github.com/aeolus-incubator/tim/wiki/Logging-in-Tim

**Comment by jguiditta** [comment]
Made a couple minor changes, otherwise, looks good, closing.
