### ISSUE TITLE
Exception Handling Guide

### ISSUE THREAD

**Issue by mtaylor** [aeolus-incubator/tim#118]
As a contributer I would like a guide to explain the exception handling process in Tim

**Comment by mtaylor** [comment]
First draft: https://github.com/aeolus-incubator/tim/wiki/Exception-Handling-in-Tim

**Comment by jguiditta** [comment]
This looks pretty good to me, but I'll read through again tomorrow and see if I can come up with any content suggestions or changes

**Comment by jguiditta** [comment]
Ok, I have read this few a couple times now, and I think it looks good.  We can always add to it over time if needed.  Closing issue
