### ISSUE TITLE
Fix parent setting issue with API

### ISSUE THREAD

**Issue by mtaylor** [aeolus-incubator/tim#53]

**Comment by jguiditta** [comment]
https://github.com/jistr/conductor/blob/api_resources_linking/src/app/util/resource_link_filter.rb
https://github.com/jistr/conductor/blob/api_resources_linking/src/app/controllers/catalogs_controller.rb#L19

**Comment by jguiditta** [comment]
This is resolved by https://github.com/aeolus-incubator/tim/pull/54
