### ISSUE TITLE
template validation raises an exception

### ISSUE THREAD

**Issue by jprovaznik** [aeolus-incubator/tim#55]
=> #<Tim::Template id: nil, xml: "asdf", created_at: nil, updated_at: nil, pool_family_id: nil>
irb(main):002:0> tpl.valid?
Nokogiri::XML::SyntaxError: Start tag expected, '<' not found
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/nokogiri-1.5.5/lib/nokogiri/xml/document.rb:54:in `read_memory'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/nokogiri-1.5.5/lib/nokogiri/xml/document.rb:54:in`parse'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/nokogiri-1.5.5/lib/nokogiri/xml.rb:33:in `XML'
    from /home/jprovazn/devel/tim/app/validators/template_validator.rb:8:in`validate'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:310:in `_callback_before_111'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:407:in`_run__3289958361602655565__validate__1238967391509302401__callbacks'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in`_run_validate_callbacks'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activemodel-3.2.9/lib/active_model/validations.rb:228:in`run_validations!'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activemodel-3.2.9/lib/active_model/validations/callbacks.rb:53:in `block in run_validations!'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:403:in`_run__3289958361602655565__validation__1238967391509302401__callbacks'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:405:in `__run_callback'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:385:in`_run_validation_callbacks'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activesupport-3.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activemodel-3.2.9/lib/active_model/validations/callbacks.rb:53:in`run_validations!'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activemodel-3.2.9/lib/active_model/validations.rb:195:in `valid?'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/activerecord-3.2.9/lib/active_record/validations.rb:69:in`valid?'
    from (irb):2
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/railties-3.2.9/lib/rails/commands/console.rb:47:in `start'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/railties-3.2.9/lib/rails/commands/console.rb:8:in`start'
    from /home/jprovazn/devel/bundle-conductor/ruby/1.9.1/gems/railties-3.2.9/lib/rails/commands.rb:41:in `<top (required)>'
    from ./script/rails:6:in`require'
    from ./script/rails:6:in `<main>'irb(main):003:0> 

template.errors should be set instead

**Comment by jguiditta** [comment]
This is fixed by above pull request
