### ISSUE TITLE
Add Delete Provider Image functionality

### ISSUE THREAD

**Issue by mtaylor** [aeolus-incubator/tim#59]
Add ability to Delete Provider Images, through integrating with factory Delete

**Comment by jguiditta** [comment]
This first rev will include:
- properly set state
- call factory
- hook up callbacks
- handle/set appropriate information on deletion failure

Deferred for later implementation:
- scalable differentiation between api user call and factory callback to object

**Comment by jguiditta** [comment]
So, there is an issue with this, in that factory objects cannot be updated, and we cannot attach a callback either on update or delete.  If we _have_ a callback already on a given object, we may get a notification, but this dos not seem a reliable assumption to make.  Factory has an issue open[1] related to this, but  am unsure if it is worth trying to hook up on the tim side until we can reliably set up callbacks, thus allowing us to know when an image has been successfully deleted by factory (or has failed for some reason).

[1] https://github.com/aeolusproject/imagefactory/issues/196
