### ISSUE TITLE
add support for respond options

### ISSUE THREAD

**Issue by jprovaznik** [aeolus-incubator/tim#63]
In some cases we would need in Conductor to redirect to different urls than what's default in REST API.
For example when we create new target image we want go back to "base image show page" instead of "new target image show" page.

It would be nice if Tim had called respond_with with options param, so:
instead of:
respond_with @base_image

there would be
respond_with(@base_image, @respond_options)

Then we can set @respond_options in before_filter. Note that default rails responder accepts options hash and one of these options is :location url which we can use.

**Comment by jguiditta** [comment]
This should be resolved by pull #66, once that is reviewed/merged
