### ISSUE TITLE
rename ProviderImage attributes - provider_account_id, provider

### ISSUE THREAD

**Issue by jprovaznik** [aeolus-incubator/tim#81]
ProviderImage model usees provider_account_id to store provider_account_identifier key retreived from imagefactory (see populate_factory_fields method). Conductor associates ProviderImage with conductor's model ProviderAccount -> so we would ideally  need provider_account_identifier for this association. 

In worst case we could use other-then-default association attribute on conductor side but  I would prefer to keep default attr names if possible.

Provider attribute doesn't confilct ATM, but could be potentially similar issue.

**Comment by jprovaznik** [comment]
Not sure how you mark blockers, bot this issue is blocker for 2.0 release.

**Comment by morazi** [comment]
Adding the 'blocker' label to this issue.

**Comment by jprovaznik** [comment]
Thanks for adding the label (I'm not a collaborator so I can't mark issues, I can only create them)

**Comment by mtaylor** [comment]
Closing this out.  Since a pull request was created and accepted.
