### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by jprovaznik** [aeolus-incubator/tim#95]
OAuth support in Tim (client mode, for sending requests to imagefactory) is needed in Conductor.  Martyn already added some oauth parts from old aeolus-image but some chunks (probably lib/aeolus_image/active_resource_oauth_client.rb which includes a monkey patch) is missing.

**Comment by jguiditta** [comment]
Might be worth checking out this gem to see if it would suit our needs: https://github.com/albertopq/oauth-activeresource

**Comment by mtaylor** [comment]
Closing this task.  It was completed as part of the above pull req
